import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cursosSidebar: [
    'inicio',
    'orden-recomendado',
    {
      type: 'autogenerated',
      dirName: 'cursos',
    },
  ],
};

export default sidebars;
